// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package mask

import (
	"errors"
	"fmt"
)

const (
	// None is a Preset of type None.
	None Preset = iota
	// Pad is a Preset of type Pad.
	Pad
	// Arrows is a Preset of type Arrows.
	Arrows
	// Modes is a Preset of type Modes.
	Modes Preset = iota + 1
	// Top is a Preset of type Top.
	Top Preset = iota + 2
	// Rows is a Preset of type Rows.
	Rows Preset = iota + 11
	// MaskAll is a Preset of type MaskAll.
	MaskAll Preset = iota + 249
)

var ErrInvalidPreset = errors.New("not a valid Preset")

const _PresetName = "NonePadArrowsModesTopRowsMaskAll"

// PresetValues returns a list of the values for Preset
func PresetValues() []Preset {
	return []Preset{
		None,
		Pad,
		Arrows,
		Modes,
		Top,
		Rows,
		MaskAll,
	}
}

var _PresetMap = map[Preset]string{
	None:    _PresetName[0:4],
	Pad:     _PresetName[4:7],
	Arrows:  _PresetName[7:13],
	Modes:   _PresetName[13:18],
	Top:     _PresetName[18:21],
	Rows:    _PresetName[21:25],
	MaskAll: _PresetName[25:32],
}

// String implements the Stringer interface.
func (x Preset) String() string {
	if str, ok := _PresetMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Preset(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Preset) IsValid() bool {
	_, ok := _PresetMap[x]
	return ok
}

var _PresetValue = map[string]Preset{
	_PresetName[0:4]:   None,
	_PresetName[4:7]:   Pad,
	_PresetName[7:13]:  Arrows,
	_PresetName[13:18]: Modes,
	_PresetName[18:21]: Top,
	_PresetName[21:25]: Rows,
	_PresetName[25:32]: MaskAll,
}

// ParsePreset attempts to convert a string to a Preset.
func ParsePreset(name string) (Preset, error) {
	if x, ok := _PresetValue[name]; ok {
		return x, nil
	}
	return Preset(0), fmt.Errorf("%s is %w", name, ErrInvalidPreset)
}
