// Code generated by go-enum
// DO NOT EDIT!

package button

import (
	"fmt"
)

const (
	// Up is a Button of type Up
	Up Button = iota
	// Down is a Button of type Down
	Down
	// Left is a Button of type Left
	Left
	// Right is a Button of type Right
	Right
	// Session is a Button of type Session
	Session
	// Drums is a Button of type Drums
	Drums
	// Keys is a Button of type Keys
	Keys
	// User is a Button of type User
	User
	// Logo is a Button of type Logo
	Logo
	// Row1 is a Button of type Row1
	Row1
	// Row2 is a Button of type Row2
	Row2
	// Row3 is a Button of type Row3
	Row3
	// Row4 is a Button of type Row4
	Row4
	// Row5 is a Button of type Row5
	Row5
	// Row6 is a Button of type Row6
	Row6
	// Row7 is a Button of type Row7
	Row7
	// StopSoloMute is a Button of type StopSoloMute
	StopSoloMute
	// Pad11 is a Button of type Pad11
	Pad11
	// Pad21 is a Button of type Pad21
	Pad21
	// Pad31 is a Button of type Pad31
	Pad31
	// Pad41 is a Button of type Pad41
	Pad41
	// Pad51 is a Button of type Pad51
	Pad51
	// Pad61 is a Button of type Pad61
	Pad61
	// Pad71 is a Button of type Pad71
	Pad71
	// Pad81 is a Button of type Pad81
	Pad81
	// Pad12 is a Button of type Pad12
	Pad12
	// Pad22 is a Button of type Pad22
	Pad22
	// Pad32 is a Button of type Pad32
	Pad32
	// Pad42 is a Button of type Pad42
	Pad42
	// Pad52 is a Button of type Pad52
	Pad52
	// Pad62 is a Button of type Pad62
	Pad62
	// Pad72 is a Button of type Pad72
	Pad72
	// Pad82 is a Button of type Pad82
	Pad82
	// Pad13 is a Button of type Pad13
	Pad13
	// Pad23 is a Button of type Pad23
	Pad23
	// Pad33 is a Button of type Pad33
	Pad33
	// Pad43 is a Button of type Pad43
	Pad43
	// Pad53 is a Button of type Pad53
	Pad53
	// Pad63 is a Button of type Pad63
	Pad63
	// Pad73 is a Button of type Pad73
	Pad73
	// Pad83 is a Button of type Pad83
	Pad83
	// Pad14 is a Button of type Pad14
	Pad14
	// Pad24 is a Button of type Pad24
	Pad24
	// Pad34 is a Button of type Pad34
	Pad34
	// Pad44 is a Button of type Pad44
	Pad44
	// Pad54 is a Button of type Pad54
	Pad54
	// Pad64 is a Button of type Pad64
	Pad64
	// Pad74 is a Button of type Pad74
	Pad74
	// Pad84 is a Button of type Pad84
	Pad84
	// Pad15 is a Button of type Pad15
	Pad15
	// Pad25 is a Button of type Pad25
	Pad25
	// Pad35 is a Button of type Pad35
	Pad35
	// Pad45 is a Button of type Pad45
	Pad45
	// Pad55 is a Button of type Pad55
	Pad55
	// Pad65 is a Button of type Pad65
	Pad65
	// Pad75 is a Button of type Pad75
	Pad75
	// Pad85 is a Button of type Pad85
	Pad85
	// Pad16 is a Button of type Pad16
	Pad16
	// Pad26 is a Button of type Pad26
	Pad26
	// Pad36 is a Button of type Pad36
	Pad36
	// Pad46 is a Button of type Pad46
	Pad46
	// Pad56 is a Button of type Pad56
	Pad56
	// Pad66 is a Button of type Pad66
	Pad66
	// Pad76 is a Button of type Pad76
	Pad76
	// Pad86 is a Button of type Pad86
	Pad86
	// Pad17 is a Button of type Pad17
	Pad17
	// Pad27 is a Button of type Pad27
	Pad27
	// Pad37 is a Button of type Pad37
	Pad37
	// Pad47 is a Button of type Pad47
	Pad47
	// Pad57 is a Button of type Pad57
	Pad57
	// Pad67 is a Button of type Pad67
	Pad67
	// Pad77 is a Button of type Pad77
	Pad77
	// Pad87 is a Button of type Pad87
	Pad87
	// Pad18 is a Button of type Pad18
	Pad18
	// Pad28 is a Button of type Pad28
	Pad28
	// Pad38 is a Button of type Pad38
	Pad38
	// Pad48 is a Button of type Pad48
	Pad48
	// Pad58 is a Button of type Pad58
	Pad58
	// Pad68 is a Button of type Pad68
	Pad68
	// Pad78 is a Button of type Pad78
	Pad78
	// Pad88 is a Button of type Pad88
	Pad88
)

const _ButtonName = "UpDownLeftRightSessionDrumsKeysUserLogoRow1Row2Row3Row4Row5Row6Row7StopSoloMutePad11Pad21Pad31Pad41Pad51Pad61Pad71Pad81Pad12Pad22Pad32Pad42Pad52Pad62Pad72Pad82Pad13Pad23Pad33Pad43Pad53Pad63Pad73Pad83Pad14Pad24Pad34Pad44Pad54Pad64Pad74Pad84Pad15Pad25Pad35Pad45Pad55Pad65Pad75Pad85Pad16Pad26Pad36Pad46Pad56Pad66Pad76Pad86Pad17Pad27Pad37Pad47Pad57Pad67Pad77Pad87Pad18Pad28Pad38Pad48Pad58Pad68Pad78Pad88"

var _ButtonMap = map[Button]string{
	0:  _ButtonName[0:2],
	1:  _ButtonName[2:6],
	2:  _ButtonName[6:10],
	3:  _ButtonName[10:15],
	4:  _ButtonName[15:22],
	5:  _ButtonName[22:27],
	6:  _ButtonName[27:31],
	7:  _ButtonName[31:35],
	8:  _ButtonName[35:39],
	9:  _ButtonName[39:43],
	10: _ButtonName[43:47],
	11: _ButtonName[47:51],
	12: _ButtonName[51:55],
	13: _ButtonName[55:59],
	14: _ButtonName[59:63],
	15: _ButtonName[63:67],
	16: _ButtonName[67:79],
	17: _ButtonName[79:84],
	18: _ButtonName[84:89],
	19: _ButtonName[89:94],
	20: _ButtonName[94:99],
	21: _ButtonName[99:104],
	22: _ButtonName[104:109],
	23: _ButtonName[109:114],
	24: _ButtonName[114:119],
	25: _ButtonName[119:124],
	26: _ButtonName[124:129],
	27: _ButtonName[129:134],
	28: _ButtonName[134:139],
	29: _ButtonName[139:144],
	30: _ButtonName[144:149],
	31: _ButtonName[149:154],
	32: _ButtonName[154:159],
	33: _ButtonName[159:164],
	34: _ButtonName[164:169],
	35: _ButtonName[169:174],
	36: _ButtonName[174:179],
	37: _ButtonName[179:184],
	38: _ButtonName[184:189],
	39: _ButtonName[189:194],
	40: _ButtonName[194:199],
	41: _ButtonName[199:204],
	42: _ButtonName[204:209],
	43: _ButtonName[209:214],
	44: _ButtonName[214:219],
	45: _ButtonName[219:224],
	46: _ButtonName[224:229],
	47: _ButtonName[229:234],
	48: _ButtonName[234:239],
	49: _ButtonName[239:244],
	50: _ButtonName[244:249],
	51: _ButtonName[249:254],
	52: _ButtonName[254:259],
	53: _ButtonName[259:264],
	54: _ButtonName[264:269],
	55: _ButtonName[269:274],
	56: _ButtonName[274:279],
	57: _ButtonName[279:284],
	58: _ButtonName[284:289],
	59: _ButtonName[289:294],
	60: _ButtonName[294:299],
	61: _ButtonName[299:304],
	62: _ButtonName[304:309],
	63: _ButtonName[309:314],
	64: _ButtonName[314:319],
	65: _ButtonName[319:324],
	66: _ButtonName[324:329],
	67: _ButtonName[329:334],
	68: _ButtonName[334:339],
	69: _ButtonName[339:344],
	70: _ButtonName[344:349],
	71: _ButtonName[349:354],
	72: _ButtonName[354:359],
	73: _ButtonName[359:364],
	74: _ButtonName[364:369],
	75: _ButtonName[369:374],
	76: _ButtonName[374:379],
	77: _ButtonName[379:384],
	78: _ButtonName[384:389],
	79: _ButtonName[389:394],
	80: _ButtonName[394:399],
}

func (i Button) String() string {
	if str, ok := _ButtonMap[i]; ok {
		return str
	}
	return fmt.Sprintf("Button(%d)", i)
}

var _ButtonValue = map[string]Button{
	_ButtonName[0:2]:     0,
	_ButtonName[2:6]:     1,
	_ButtonName[6:10]:    2,
	_ButtonName[10:15]:   3,
	_ButtonName[15:22]:   4,
	_ButtonName[22:27]:   5,
	_ButtonName[27:31]:   6,
	_ButtonName[31:35]:   7,
	_ButtonName[35:39]:   8,
	_ButtonName[39:43]:   9,
	_ButtonName[43:47]:   10,
	_ButtonName[47:51]:   11,
	_ButtonName[51:55]:   12,
	_ButtonName[55:59]:   13,
	_ButtonName[59:63]:   14,
	_ButtonName[63:67]:   15,
	_ButtonName[67:79]:   16,
	_ButtonName[79:84]:   17,
	_ButtonName[84:89]:   18,
	_ButtonName[89:94]:   19,
	_ButtonName[94:99]:   20,
	_ButtonName[99:104]:  21,
	_ButtonName[104:109]: 22,
	_ButtonName[109:114]: 23,
	_ButtonName[114:119]: 24,
	_ButtonName[119:124]: 25,
	_ButtonName[124:129]: 26,
	_ButtonName[129:134]: 27,
	_ButtonName[134:139]: 28,
	_ButtonName[139:144]: 29,
	_ButtonName[144:149]: 30,
	_ButtonName[149:154]: 31,
	_ButtonName[154:159]: 32,
	_ButtonName[159:164]: 33,
	_ButtonName[164:169]: 34,
	_ButtonName[169:174]: 35,
	_ButtonName[174:179]: 36,
	_ButtonName[179:184]: 37,
	_ButtonName[184:189]: 38,
	_ButtonName[189:194]: 39,
	_ButtonName[194:199]: 40,
	_ButtonName[199:204]: 41,
	_ButtonName[204:209]: 42,
	_ButtonName[209:214]: 43,
	_ButtonName[214:219]: 44,
	_ButtonName[219:224]: 45,
	_ButtonName[224:229]: 46,
	_ButtonName[229:234]: 47,
	_ButtonName[234:239]: 48,
	_ButtonName[239:244]: 49,
	_ButtonName[244:249]: 50,
	_ButtonName[249:254]: 51,
	_ButtonName[254:259]: 52,
	_ButtonName[259:264]: 53,
	_ButtonName[264:269]: 54,
	_ButtonName[269:274]: 55,
	_ButtonName[274:279]: 56,
	_ButtonName[279:284]: 57,
	_ButtonName[284:289]: 58,
	_ButtonName[289:294]: 59,
	_ButtonName[294:299]: 60,
	_ButtonName[299:304]: 61,
	_ButtonName[304:309]: 62,
	_ButtonName[309:314]: 63,
	_ButtonName[314:319]: 64,
	_ButtonName[319:324]: 65,
	_ButtonName[324:329]: 66,
	_ButtonName[329:334]: 67,
	_ButtonName[334:339]: 68,
	_ButtonName[339:344]: 69,
	_ButtonName[344:349]: 70,
	_ButtonName[349:354]: 71,
	_ButtonName[354:359]: 72,
	_ButtonName[359:364]: 73,
	_ButtonName[364:369]: 74,
	_ButtonName[369:374]: 75,
	_ButtonName[374:379]: 76,
	_ButtonName[379:384]: 77,
	_ButtonName[384:389]: 78,
	_ButtonName[389:394]: 79,
	_ButtonName[394:399]: 80,
}

// ParseButton attempts to convert a string to a Button
func ParseButton(name string) (Button, error) {
	if x, ok := _ButtonValue[name]; ok {
		return Button(x), nil
	}
	return Button(0), fmt.Errorf("%s is not a valid Button", name)
}
