// Code generated by go-enum
// DO NOT EDIT!

package minimk3

import (
	"fmt"
)

const (
	// BtnUp is a Btn of type Up
	BtnUp Btn = iota
	// BtnDown is a Btn of type Down
	BtnDown
	// BtnLeft is a Btn of type Left
	BtnLeft
	// BtnRight is a Btn of type Right
	BtnRight
	// BtnSession is a Btn of type Session
	BtnSession
	// BtnDrums is a Btn of type Drums
	BtnDrums
	// BtnKeys is a Btn of type Keys
	BtnKeys
	// BtnUser is a Btn of type User
	BtnUser
	// BtnLogo is a Btn of type Logo
	BtnLogo
	// BtnRow1 is a Btn of type Row1
	BtnRow1
	// BtnRow2 is a Btn of type Row2
	BtnRow2
	// BtnRow3 is a Btn of type Row3
	BtnRow3
	// BtnRow4 is a Btn of type Row4
	BtnRow4
	// BtnRow5 is a Btn of type Row5
	BtnRow5
	// BtnRow6 is a Btn of type Row6
	BtnRow6
	// BtnRow7 is a Btn of type Row7
	BtnRow7
	// BtnStopSoloMute is a Btn of type StopSoloMute
	BtnStopSoloMute
	// BtnPad11 is a Btn of type Pad11
	BtnPad11
	// BtnPad12 is a Btn of type Pad12
	BtnPad12
	// BtnPad13 is a Btn of type Pad13
	BtnPad13
	// BtnPad14 is a Btn of type Pad14
	BtnPad14
	// BtnPad15 is a Btn of type Pad15
	BtnPad15
	// BtnPad16 is a Btn of type Pad16
	BtnPad16
	// BtnPad17 is a Btn of type Pad17
	BtnPad17
	// BtnPad18 is a Btn of type Pad18
	BtnPad18
	// BtnPad21 is a Btn of type Pad21
	BtnPad21
	// BtnPad22 is a Btn of type Pad22
	BtnPad22
	// BtnPad23 is a Btn of type Pad23
	BtnPad23
	// BtnPad24 is a Btn of type Pad24
	BtnPad24
	// BtnPad25 is a Btn of type Pad25
	BtnPad25
	// BtnPad26 is a Btn of type Pad26
	BtnPad26
	// BtnPad27 is a Btn of type Pad27
	BtnPad27
	// BtnPad28 is a Btn of type Pad28
	BtnPad28
	// BtnPad31 is a Btn of type Pad31
	BtnPad31
	// BtnPad32 is a Btn of type Pad32
	BtnPad32
	// BtnPad33 is a Btn of type Pad33
	BtnPad33
	// BtnPad34 is a Btn of type Pad34
	BtnPad34
	// BtnPad35 is a Btn of type Pad35
	BtnPad35
	// BtnPad36 is a Btn of type Pad36
	BtnPad36
	// BtnPad37 is a Btn of type Pad37
	BtnPad37
	// BtnPad38 is a Btn of type Pad38
	BtnPad38
	// BtnPad41 is a Btn of type Pad41
	BtnPad41
	// BtnPad42 is a Btn of type Pad42
	BtnPad42
	// BtnPad43 is a Btn of type Pad43
	BtnPad43
	// BtnPad44 is a Btn of type Pad44
	BtnPad44
	// BtnPad45 is a Btn of type Pad45
	BtnPad45
	// BtnPad46 is a Btn of type Pad46
	BtnPad46
	// BtnPad47 is a Btn of type Pad47
	BtnPad47
	// BtnPad48 is a Btn of type Pad48
	BtnPad48
	// BtnPad51 is a Btn of type Pad51
	BtnPad51
	// BtnPad52 is a Btn of type Pad52
	BtnPad52
	// BtnPad53 is a Btn of type Pad53
	BtnPad53
	// BtnPad54 is a Btn of type Pad54
	BtnPad54
	// BtnPad55 is a Btn of type Pad55
	BtnPad55
	// BtnPad56 is a Btn of type Pad56
	BtnPad56
	// BtnPad57 is a Btn of type Pad57
	BtnPad57
	// BtnPad58 is a Btn of type Pad58
	BtnPad58
	// BtnPad61 is a Btn of type Pad61
	BtnPad61
	// BtnPad62 is a Btn of type Pad62
	BtnPad62
	// BtnPad63 is a Btn of type Pad63
	BtnPad63
	// BtnPad64 is a Btn of type Pad64
	BtnPad64
	// BtnPad65 is a Btn of type Pad65
	BtnPad65
	// BtnPad66 is a Btn of type Pad66
	BtnPad66
	// BtnPad67 is a Btn of type Pad67
	BtnPad67
	// BtnPad68 is a Btn of type Pad68
	BtnPad68
	// BtnPad71 is a Btn of type Pad71
	BtnPad71
	// BtnPad72 is a Btn of type Pad72
	BtnPad72
	// BtnPad73 is a Btn of type Pad73
	BtnPad73
	// BtnPad74 is a Btn of type Pad74
	BtnPad74
	// BtnPad75 is a Btn of type Pad75
	BtnPad75
	// BtnPad76 is a Btn of type Pad76
	BtnPad76
	// BtnPad77 is a Btn of type Pad77
	BtnPad77
	// BtnPad78 is a Btn of type Pad78
	BtnPad78
	// BtnPad81 is a Btn of type Pad81
	BtnPad81
	// BtnPad82 is a Btn of type Pad82
	BtnPad82
	// BtnPad83 is a Btn of type Pad83
	BtnPad83
	// BtnPad84 is a Btn of type Pad84
	BtnPad84
	// BtnPad85 is a Btn of type Pad85
	BtnPad85
	// BtnPad86 is a Btn of type Pad86
	BtnPad86
	// BtnPad87 is a Btn of type Pad87
	BtnPad87
	// BtnPad88 is a Btn of type Pad88
	BtnPad88
)

const _BtnName = "UpDownLeftRightSessionDrumsKeysUserLogoRow1Row2Row3Row4Row5Row6Row7StopSoloMutePad11Pad12Pad13Pad14Pad15Pad16Pad17Pad18Pad21Pad22Pad23Pad24Pad25Pad26Pad27Pad28Pad31Pad32Pad33Pad34Pad35Pad36Pad37Pad38Pad41Pad42Pad43Pad44Pad45Pad46Pad47Pad48Pad51Pad52Pad53Pad54Pad55Pad56Pad57Pad58Pad61Pad62Pad63Pad64Pad65Pad66Pad67Pad68Pad71Pad72Pad73Pad74Pad75Pad76Pad77Pad78Pad81Pad82Pad83Pad84Pad85Pad86Pad87Pad88"

var _BtnMap = map[Btn]string{
	0:  _BtnName[0:2],
	1:  _BtnName[2:6],
	2:  _BtnName[6:10],
	3:  _BtnName[10:15],
	4:  _BtnName[15:22],
	5:  _BtnName[22:27],
	6:  _BtnName[27:31],
	7:  _BtnName[31:35],
	8:  _BtnName[35:39],
	9:  _BtnName[39:43],
	10: _BtnName[43:47],
	11: _BtnName[47:51],
	12: _BtnName[51:55],
	13: _BtnName[55:59],
	14: _BtnName[59:63],
	15: _BtnName[63:67],
	16: _BtnName[67:79],
	17: _BtnName[79:84],
	18: _BtnName[84:89],
	19: _BtnName[89:94],
	20: _BtnName[94:99],
	21: _BtnName[99:104],
	22: _BtnName[104:109],
	23: _BtnName[109:114],
	24: _BtnName[114:119],
	25: _BtnName[119:124],
	26: _BtnName[124:129],
	27: _BtnName[129:134],
	28: _BtnName[134:139],
	29: _BtnName[139:144],
	30: _BtnName[144:149],
	31: _BtnName[149:154],
	32: _BtnName[154:159],
	33: _BtnName[159:164],
	34: _BtnName[164:169],
	35: _BtnName[169:174],
	36: _BtnName[174:179],
	37: _BtnName[179:184],
	38: _BtnName[184:189],
	39: _BtnName[189:194],
	40: _BtnName[194:199],
	41: _BtnName[199:204],
	42: _BtnName[204:209],
	43: _BtnName[209:214],
	44: _BtnName[214:219],
	45: _BtnName[219:224],
	46: _BtnName[224:229],
	47: _BtnName[229:234],
	48: _BtnName[234:239],
	49: _BtnName[239:244],
	50: _BtnName[244:249],
	51: _BtnName[249:254],
	52: _BtnName[254:259],
	53: _BtnName[259:264],
	54: _BtnName[264:269],
	55: _BtnName[269:274],
	56: _BtnName[274:279],
	57: _BtnName[279:284],
	58: _BtnName[284:289],
	59: _BtnName[289:294],
	60: _BtnName[294:299],
	61: _BtnName[299:304],
	62: _BtnName[304:309],
	63: _BtnName[309:314],
	64: _BtnName[314:319],
	65: _BtnName[319:324],
	66: _BtnName[324:329],
	67: _BtnName[329:334],
	68: _BtnName[334:339],
	69: _BtnName[339:344],
	70: _BtnName[344:349],
	71: _BtnName[349:354],
	72: _BtnName[354:359],
	73: _BtnName[359:364],
	74: _BtnName[364:369],
	75: _BtnName[369:374],
	76: _BtnName[374:379],
	77: _BtnName[379:384],
	78: _BtnName[384:389],
	79: _BtnName[389:394],
	80: _BtnName[394:399],
}

func (i Btn) String() string {
	if str, ok := _BtnMap[i]; ok {
		return str
	}
	return fmt.Sprintf("Btn(%d)", i)
}

var _BtnValue = map[string]Btn{
	_BtnName[0:2]:     0,
	_BtnName[2:6]:     1,
	_BtnName[6:10]:    2,
	_BtnName[10:15]:   3,
	_BtnName[15:22]:   4,
	_BtnName[22:27]:   5,
	_BtnName[27:31]:   6,
	_BtnName[31:35]:   7,
	_BtnName[35:39]:   8,
	_BtnName[39:43]:   9,
	_BtnName[43:47]:   10,
	_BtnName[47:51]:   11,
	_BtnName[51:55]:   12,
	_BtnName[55:59]:   13,
	_BtnName[59:63]:   14,
	_BtnName[63:67]:   15,
	_BtnName[67:79]:   16,
	_BtnName[79:84]:   17,
	_BtnName[84:89]:   18,
	_BtnName[89:94]:   19,
	_BtnName[94:99]:   20,
	_BtnName[99:104]:  21,
	_BtnName[104:109]: 22,
	_BtnName[109:114]: 23,
	_BtnName[114:119]: 24,
	_BtnName[119:124]: 25,
	_BtnName[124:129]: 26,
	_BtnName[129:134]: 27,
	_BtnName[134:139]: 28,
	_BtnName[139:144]: 29,
	_BtnName[144:149]: 30,
	_BtnName[149:154]: 31,
	_BtnName[154:159]: 32,
	_BtnName[159:164]: 33,
	_BtnName[164:169]: 34,
	_BtnName[169:174]: 35,
	_BtnName[174:179]: 36,
	_BtnName[179:184]: 37,
	_BtnName[184:189]: 38,
	_BtnName[189:194]: 39,
	_BtnName[194:199]: 40,
	_BtnName[199:204]: 41,
	_BtnName[204:209]: 42,
	_BtnName[209:214]: 43,
	_BtnName[214:219]: 44,
	_BtnName[219:224]: 45,
	_BtnName[224:229]: 46,
	_BtnName[229:234]: 47,
	_BtnName[234:239]: 48,
	_BtnName[239:244]: 49,
	_BtnName[244:249]: 50,
	_BtnName[249:254]: 51,
	_BtnName[254:259]: 52,
	_BtnName[259:264]: 53,
	_BtnName[264:269]: 54,
	_BtnName[269:274]: 55,
	_BtnName[274:279]: 56,
	_BtnName[279:284]: 57,
	_BtnName[284:289]: 58,
	_BtnName[289:294]: 59,
	_BtnName[294:299]: 60,
	_BtnName[299:304]: 61,
	_BtnName[304:309]: 62,
	_BtnName[309:314]: 63,
	_BtnName[314:319]: 64,
	_BtnName[319:324]: 65,
	_BtnName[324:329]: 66,
	_BtnName[329:334]: 67,
	_BtnName[334:339]: 68,
	_BtnName[339:344]: 69,
	_BtnName[344:349]: 70,
	_BtnName[349:354]: 71,
	_BtnName[354:359]: 72,
	_BtnName[359:364]: 73,
	_BtnName[364:369]: 74,
	_BtnName[369:374]: 75,
	_BtnName[374:379]: 76,
	_BtnName[379:384]: 77,
	_BtnName[384:389]: 78,
	_BtnName[389:394]: 79,
	_BtnName[394:399]: 80,
}

// ParseBtn attempts to convert a string to a Btn
func ParseBtn(name string) (Btn, error) {
	if x, ok := _BtnValue[name]; ok {
		return Btn(x), nil
	}
	return Btn(0), fmt.Errorf("%s is not a valid Btn", name)
}
