// Code generated by go-enum
// DO NOT EDIT!

package minimk3

import (
	"fmt"
)

const (
	// EventTypePressed is a EventType of type Pressed
	EventTypePressed EventType = iota
	// EventTypeReleased is a EventType of type Released
	EventTypeReleased
)

const _EventTypeName = "PressedReleased"

var _EventTypeMap = map[EventType]string{
	0: _EventTypeName[0:7],
	1: _EventTypeName[7:15],
}

func (i EventType) String() string {
	if str, ok := _EventTypeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("EventType(%d)", i)
}

var _EventTypeValue = map[string]EventType{
	_EventTypeName[0:7]:  0,
	_EventTypeName[7:15]: 1,
}

// ParseEventType attempts to convert a string to a EventType
func ParseEventType(name string) (EventType, error) {
	if x, ok := _EventTypeValue[name]; ok {
		return EventType(x), nil
	}
	return EventType(0), fmt.Errorf("%s is not a valid EventType", name)
}
