// Code generated by go-enum
// DO NOT EDIT!

package cmd

import (
	"fmt"
)

const (
	// DeviceInquiry is a Cmd of type DeviceInquiry
	DeviceInquiry Cmd = iota
	// EnableSession is a Cmd of type EnableSession
	EnableSession
	// ProgrammerMode is a Cmd of type ProgrammerMode
	ProgrammerMode
	// SelectLayout is a Cmd of type SelectLayout
	SelectLayout
	// BrightnessLevel is a Cmd of type BrightnessLevel
	BrightnessLevel
	// ClearDawState is a Cmd of type ClearDawState
	ClearDawState
	// SessionColor is a Cmd of type SessionColor
	SessionColor
	// TextScrolling is a Cmd of type TextScrolling
	TextScrolling
	// LedColor is a Cmd of type LedColor
	LedColor
	// Sleep is a Cmd of type Sleep
	Sleep
)

const _CmdName = "DeviceInquiryEnableSessionProgrammerModeSelectLayoutBrightnessLevelClearDawStateSessionColorTextScrollingLedColorSleep"

var _CmdMap = map[Cmd]string{
	0: _CmdName[0:13],
	1: _CmdName[13:26],
	2: _CmdName[26:40],
	3: _CmdName[40:52],
	4: _CmdName[52:67],
	5: _CmdName[67:80],
	6: _CmdName[80:92],
	7: _CmdName[92:105],
	8: _CmdName[105:113],
	9: _CmdName[113:118],
}

func (i Cmd) String() string {
	if str, ok := _CmdMap[i]; ok {
		return str
	}
	return fmt.Sprintf("Cmd(%d)", i)
}

var _CmdValue = map[string]Cmd{
	_CmdName[0:13]:    0,
	_CmdName[13:26]:   1,
	_CmdName[26:40]:   2,
	_CmdName[40:52]:   3,
	_CmdName[52:67]:   4,
	_CmdName[67:80]:   5,
	_CmdName[80:92]:   6,
	_CmdName[92:105]:  7,
	_CmdName[105:113]: 8,
	_CmdName[113:118]: 9,
}

// ParseCmd attempts to convert a string to a Cmd
func ParseCmd(name string) (Cmd, error) {
	if x, ok := _CmdValue[name]; ok {
		return Cmd(x), nil
	}
	return Cmd(0), fmt.Errorf("%s is not a valid Cmd", name)
}
