// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package layout

import (
	"errors"
	"fmt"
)

const (
	// RowPressed is a HandlerType of type RowPressed.
	RowPressed HandlerType = iota
	// RowHold is a HandlerType of type RowHold.
	RowHold
	// RowReleased is a HandlerType of type RowReleased.
	RowReleased
	// PadPressed is a HandlerType of type PadPressed.
	PadPressed
	// PadHold is a HandlerType of type PadHold.
	PadHold
	// PadReleased is a HandlerType of type PadReleased.
	PadReleased
	// ModePressed is a HandlerType of type ModePressed.
	ModePressed
	// ModeHold is a HandlerType of type ModeHold.
	ModeHold
	// ModeReleased is a HandlerType of type ModeReleased.
	ModeReleased
	// ArrowPressed is a HandlerType of type ArrowPressed.
	ArrowPressed
	// ArrowHold is a HandlerType of type ArrowHold.
	ArrowHold
	// ArrowReleased is a HandlerType of type ArrowReleased.
	ArrowReleased
)

var ErrInvalidHandlerType = errors.New("not a valid HandlerType")

const _HandlerTypeName = "RowPressedRowHoldRowReleasedPadPressedPadHoldPadReleasedModePressedModeHoldModeReleasedArrowPressedArrowHoldArrowReleased"

var _HandlerTypeMap = map[HandlerType]string{
	RowPressed:    _HandlerTypeName[0:10],
	RowHold:       _HandlerTypeName[10:17],
	RowReleased:   _HandlerTypeName[17:28],
	PadPressed:    _HandlerTypeName[28:38],
	PadHold:       _HandlerTypeName[38:45],
	PadReleased:   _HandlerTypeName[45:56],
	ModePressed:   _HandlerTypeName[56:67],
	ModeHold:      _HandlerTypeName[67:75],
	ModeReleased:  _HandlerTypeName[75:87],
	ArrowPressed:  _HandlerTypeName[87:99],
	ArrowHold:     _HandlerTypeName[99:108],
	ArrowReleased: _HandlerTypeName[108:121],
}

// String implements the Stringer interface.
func (x HandlerType) String() string {
	if str, ok := _HandlerTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("HandlerType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x HandlerType) IsValid() bool {
	_, ok := _HandlerTypeMap[x]
	return ok
}

var _HandlerTypeValue = map[string]HandlerType{
	_HandlerTypeName[0:10]:    RowPressed,
	_HandlerTypeName[10:17]:   RowHold,
	_HandlerTypeName[17:28]:   RowReleased,
	_HandlerTypeName[28:38]:   PadPressed,
	_HandlerTypeName[38:45]:   PadHold,
	_HandlerTypeName[45:56]:   PadReleased,
	_HandlerTypeName[56:67]:   ModePressed,
	_HandlerTypeName[67:75]:   ModeHold,
	_HandlerTypeName[75:87]:   ModeReleased,
	_HandlerTypeName[87:99]:   ArrowPressed,
	_HandlerTypeName[99:108]:  ArrowHold,
	_HandlerTypeName[108:121]: ArrowReleased,
}

// ParseHandlerType attempts to convert a string to a HandlerType.
func ParseHandlerType(name string) (HandlerType, error) {
	if x, ok := _HandlerTypeValue[name]; ok {
		return x, nil
	}
	return HandlerType(0), fmt.Errorf("%s is %w", name, ErrInvalidHandlerType)
}
